app:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - elasticsearch
    - memcached
    - redis

postgres:
  image: postgres:9.4
  ports:
    - "5432"

elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    ES_JAVA_OPTS: "-Xms1g -Xmx1g"

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - drkiq-redis:/var/lib/redis/data
